repos:
  - name: OpenvCloud Core
    source:
       branch: '246_patch_releases'
    target:
       tag: v2.4.6.2
    url: git@git.gig.tech:openvcloud/openvcloud
  - name: OpenvCloud Installer
    source:
       branch: 'master'
    target:
       tag: v2.4.6.1
    url: git@git.gig.tech:openvcloud/openvcloud_installer
  - name: OpenvCloud Frontend
    source:
       branch: master
    target:
       tag: v2.4.6
    url: git@git.gig.tech:openvcloud/g8vdc
  - name: OpenvCloud 0-Access
    source:
       branch: master
    target:
       tag: v2.4.6
    url: git@git.gig.tech:openvcloud/0-access
  - name: OpenvCloud noVNC
    source:
       branch: master
    target:
       branch: 0.5.1
    url: git@git.gig.tech:openvcloud/noVNC
  - name: JumpScale Core
    source:
       branch: master
    target:
       tag: v7.4.6
    url: git@git.gig.tech:openvcloud/jumpscale/jumpscale_core7
  - name: JumpScale Portal
    source:
       branch: master
    target:
       tag: v7.4.6
    url: git@git.gig.tech:openvcloud/jumpscale/jumpscale_portal
  - name: Python Binaries
    source:
       branch: master
    target:
       tag: v2.4.6
    url: git@git.gig.tech:openvcloud/binary/python
  - name: OpenvStorage Branding
    source:
       branch: master
    target:
       tag: v2.4.6
    url: git@git.gig.tech:openvcloud/binary/openvstorage_branding
  - name: RouterOS Binary
    source:
       branch: master
    target:
       tag: v2.4.6
    url: git@git.gig.tech:openvcloud/binary/routeros

images:
  ovcimages/openvcloud/cb_master: 2.4.6.2
  ovcimages/openvcloud/vgw: 2.4.6
  ovcimages/openvcloud/importexport: 2.4.6
  ovcimages/openvcloud/base: 2.4.6.1
  ovcimages/openvcloud/grafana-init: 2.4.6
  ovcimages/openvcloud/syncthing_sidecar: 2.4.6
  ovcimages/openvcloud/slightcar: 2.4.6
  ovcimages/openvcloud/pxeboot: 2.4.6
  ovcimages/openvcloud/pxeboot-init: 2.4.6
  ovcimages/openvcloud/pxeboot-base: 2.4.6
  ovcimages/openvcloud/pxeboot-httpd: 2.4.6
  ovcimages/openvcloud/nginx: 2.4.6
  ovcimages/openvcloud/nginx-init: 2.4.6
  ovcimages/openvcloud/0-access: 2.4.6
  ovcimages/openvcloud/management: 2.4.6.1
  ovcimages/openvcloud/apt-mirror: 2.4.6
  ovcimages/openvcloud/ovc-versions: latest
  ovcimages/3rdparty/grafana: 5.0.0
  ovcimages/3rdparty/mongo: 3.7.2
  ovcimages/3rdparty/mongo-k8s-sidecar: latest
  ovcimages/3rdparty/influxdb: 1.4
  ovcimages/3rdparty/syncthing: latest
  ovcimages/3rdparty/redis: 3.2

upgrade:
  apiVersion: batch/v1
  kind: Job
  metadata:
    name: upgradejob
  spec:
    template:
      metadata:
        labels:
          app: upgrader
      spec:
        restartPolicy: Never
        initContainers:
        - name: nginx-init
          command: [jspython]
          args: ['configure-nginx.py', '--upgrade']
          image: ovcimages/openvcloud/nginx-init
          imagePullPolicy: Always
          workingDir: /var/run/scripts/nginx
          volumeMounts:
          - name: nginx-config
            mountPath:  /opt/cfg/nginx/sites-enabled
          - name:  system-config
            mountPath:  /opt/cfg/system/system-config.yaml
            subPath: system-config.yaml
          - name: update-files
            mountPath:  /opt/cfg/upgrade
          - name: update-log
            mountPath: /opt/logs
        containers:
        - name: upgrader-container
          image: ovcimages/openvcloud/management
          imagePullPolicy: Always
          volumeMounts:
          - name: ssh-dir
            mountPath: /root/.ssh
          - name: update-log
            mountPath: /opt/logs
          - name:  system-config
            mountPath:  /opt/cfg/system/system-config.yaml
            subPath: system-config.yaml
          - name: kube-client
            mountPath: /usr/local/bin/kubectl
            subPath: kubectl
          command: [bash]
          args: [update_env]
          workingDir: /opt/code/git.gig.tech/openvcloud/openvcloud_installer/scripts/install/
        - name: server-container
          image: ovcimages/openvcloud/nginx
          ports:
          - containerPort: 80
          volumeMounts:
          - name: update-files
            mountPath: /opt/cfg/upgrade
          - name: update-log
            mountPath: /opt/logs
          - name: nginx-config
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
          - name: certs
            mountPath: /opt/cfg/nginx/ssl/
            readOnly: true
        volumes:
        - name: ssh-dir
          hostPath:
            path: /var/ovc/.ssh
            type: Directory
        - name: update-log
          hostPath:
            path: /var/ovc/updatelogs
            type: Directory
        - name: update-files
          emptyDir: {}
        - name: system-config
          configMap:
            name: system-config
        - name: nginx-config
          emptyDir: {}
        - name: certs
          hostPath:
            path: /var/ovc/ssl/
            type: Directory
        - name: kube-client
          hostPath:
            path: /usr/local/bin
            type: Directory
  
  
